# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brands_created_at_alter_brands_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
    ]
