# Generated by Django 4.2.3 on 2023-10-09 16:40

import brands.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brands_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='photo',
            field=models.ImageField(null=True, upload_to=brands.models.upload_photo),
        ),
    ]
