# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver')])),
                ('local_sell', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='sell')),
                ('world_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='world sell')),
                ('local_buy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='world buy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
