# Generated by Django 4.2.3 on 2023-08-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'verbose_name': 'pricing', 'verbose_name_plural': 'pricing'},
        ),
        migrations.AddField(
            model_name='pricing',
            name='world_buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='world buy'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='local_buy',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='buy'),
            preserve_default=False,
        ),
    ]
