# Generated by Django 4.2.3 on 2023-08-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_pricing_options_pricing_world_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='old',
            field=models.BooleanField(default=False),
        ),
    ]
