# Generated by Django 4.2.3 on 2023-08-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricing_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'ordering': ('-created_at',), 'verbose_name': 'pricing', 'verbose_name_plural': 'pricing'},
        ),
    ]
