# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_alter_favorites_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
    ]
