# Generated by Django 4.2.3 on 2023-11-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufactureFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type', models.SmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver')])),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'manufacture fees',
                'verbose_name_plural': 'manufacture fees',
                'unique_together': {('type', 'weight')},
            },
        ),
    ]
