# Generated by Django 4.2.3 on 2023-11-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal_types', '0004_metaltypes_photo'),
        ('manufacture_fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturefees',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='manufacture_fees', to='metal_types.metaltypes'),
        ),
    ]
