# Generated by Django 4.2.3 on 2023-11-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture_fees', '0002_alter_manufacturefees_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturefees',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
