# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal_types', '0002_alter_metaltypes_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metaltypes',
            options={'verbose_name': 'metal type', 'verbose_name_plural': 'metal types'},
        ),
    ]
