# Generated by Django 4.2.3 on 2023-10-09 16:40

from django.db import migrations, models
import metal_types.models


class Migration(migrations.Migration):

    dependencies = [
        ('metal_types', '0003_alter_metaltypes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaltypes',
            name='photo',
            field=models.ImageField(null=True, upload_to=metal_types.models.upload_photo),
        ),
    ]
