# Generated by Django 4.2.1 on 2023-06-04 20:27

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.SmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver')])),
                ('world_sell_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('world_buy_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('local_sell_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('local_buy_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
