# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charts',
            options={'ordering': ('created_at',), 'verbose_name': 'chart', 'verbose_name_plural': 'charts'},
        ),
    ]
