# Generated by Django 4.2.1 on 2023-05-24 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_body', models.TextField()),
                ('answer', models.TextField()),
                ('num_useful', models.BigIntegerField(default=0)),
                ('num_unuseful', models.BigIntegerField(default=0)),
                ('sort_order', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
