# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_alter_faqs_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqs',
            options={'ordering': ('sort_order',), 'verbose_name': 'faqs', 'verbose_name_plural': 'faqs'},
        ),
    ]
