# Generated by Django 4.2.1 on 2023-05-24 14:33

from django.db import migrations, models
import testimonies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
                ('image', models.ImageField(upload_to=testimonies.models.upload_photo)),
                ('full_name', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('screenshot', models.ImageField(upload_to=testimonies.models.upload_screenshot)),
                ('testimony_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
