# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_alter_testimonies_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonies',
            options={'verbose_name': 'testimony', 'verbose_name_plural': 'testimonies'},
        ),
    ]
