# Generated by Django 4.2.1 on 2023-05-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address_line_1', models.CharField(max_length=400)),
                ('address_line_2', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(max_length=200)),
                ('governorate', models.CharField(max_length=200)),
                ('working_time', models.TextField()),
            ],
        ),
    ]
