# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_city_governorate_alter_locations_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'governorate', 'verbose_name_plural': 'governorates'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
    ]
