# Generated by Django 4.2.1 on 2023-05-24 14:33

import balances.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField()),
                ('purchase_price', models.FloatField()),
                ('gm_price', models.FloatField()),
                ('packing_per_gm', models.FloatField()),
                ('cashback_per_gm', models.FloatField()),
                ('is_available', models.BooleanField(default=True)),
                ('bill_scan', models.ImageField(upload_to=balances.models.upload_bill_scan)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
