# Generated by Django 4.2.3 on 2023-08-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balances',
            options={'verbose_name': 'balance', 'verbose_name_plural': 'balances'},
        ),
    ]
