# Generated by Django 4.2.1 on 2023-05-24 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('metal_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('created_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('weight', models.FloatField()),
                ('kirat', models.FloatField()),
                ('fitness', models.FloatField()),
                ('is_available', models.BooleanField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands')),
                ('metal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal_types.metaltypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
