# Generated by Django 4.2.3 on 2023-10-09 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to=products.models.upload_photo)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
            options={
                'verbose_name': 'product photos',
                'verbose_name_plural': 'product photos',
            },
        ),
    ]
