# Generated by Django 4.2.3 on 2023-10-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.products'),
        ),
    ]
