# Generated by Django 4.2.3 on 2023-10-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productphotos_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
