# Generated by Django 4.2.3 on 2023-11-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_fitness_alter_products_kirat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fitness',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='kirat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='weight',
            field=models.FloatField(),
        ),
    ]
